### ISSUE TITLE
Cannot fine module error after upgrade to 2.5.1

### ISSUE THREAD

**Issue by jbojcic1** [cashubtc/cashu-ts#303]
After upgrading from 2.4.2 to 2.5.1 I started getting bunch of errors like:
```
8:16:24 PM [vite] Error when evaluating SSR module /app/lib/cashu/token.ts: failed to import "@cashu/cashu-ts"
|- Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/jbojcic/Projects/prism/boardwalkcash/node_modules/@cashu/cashu-ts/lib/buffer/index.jsx' imported from /Users/jbojcic/Projects/prism/boardwalkcash/node_modules/@cashu/cashu-ts/lib/cashu-ts.es.js
    at finalizeResolution (node:internal/modules/esm/resolve:275:11)
    at moduleResolve (node:internal/modules/esm/resolve:860:10)
    at defaultResolve (node:internal/modules/esm/resolve:984:11)
    at nextResolve (node:internal/modules/esm/hooks:748:28)
    at resolveExtensions (file:///Users/jbojcic/Projects/prism/boardwalkcash/node_modules/tsx/dist/esm/index.mjs?1746814579825:2:2938)
    at async resolveDirectory (file:///Users/jbojcic/Projects/prism/boardwalkcash/node_modules/tsx/dist/esm/index.mjs?1746814579825:2:3538)
    at async resolve (file:///Users/jbojcic/Projects/prism/boardwalkcash/node_modules/tsx/dist/esm/index.mjs?1746814579825:2:4441)
    at async nextResolve (node:internal/modules/esm/hooks:748:22)
    at async Hooks.resolve (node:internal/modules/esm/hooks:240:24)
    at async handleMessage (node:internal/modules/esm/worker:199:18)
```

I suspect that there is some issue caused by [this pr](https://github.com/cashubtc/cashu-ts/pull/279) and something wrong with [this buffer import](https://github.com/cashubtc/cashu-ts/pull/279/files#diff-d0dce76e83a07709eb3481413012471a2121789861bffd69539c5addaf67e11dR6)

**Comment by Egge21M** [comment]
Thanks for raising this. Can you please check if 2.5.2 resolves this issue?

**Comment by jbojcic1** [comment]
@Egge21M Yes that fixed it, thx. 

Unrelated question. Since crypto is now moved back to cashu-ts should cashu-ts export all the same stuff that was exported there? E.g. we are using `import { hashToCurve } from '@cashu/crypto/modules/common';` but I don't see it exported from the cashu-ts so we still need to install `@cashu/crypto` package.

**Comment by Egge21M** [comment]
@jbojcic1 awesome! Yes, that is the plan. I guess the PR to move it back in was a bit premature, but we are working on unifying the types and exports already. This will be resolved soon. In the meantime keeping the crypto lib around is a great workaround.
