### ISSUE TITLE
Web socket subscription cancel throws

### ISSUE THREAD

**Issue by jbojcic1** [cashubtc/cashu-ts#301]
Currently the code creates a subscription looks like this:
```
	createSubscription(
		params: Omit<JsonRpcReqParams, 'subId'>,
		callback: (payload: any) => any,
		errorCallback: (e: Error) => any
	) {
		if (this.ws?.readyState !== 1) {
			return errorCallback(new Error('Socket is not open'));
		}
		const subId = (Math.random() + 1).toString(36).substring(7);
		this.addRpcListener(
			() => {
				this.addSubListener(subId, callback);
			},
			(e: JsonRpcErrorObject) => {
				errorCallback(new Error(e.message));
			},
			this.rpcId
		);
		this.sendRequest('subscribe', { ...params, subId });
		this.rpcId++;
		return subId;
	}
```

callback passed to addRpcListener which adds a listener for the subId is executed at some point later only after the subId is already returned to the caller. This means that if the caller calls cancel on the subscription shortly after the create subscription was called, the cancelSubscription will call removeListener which looks like this:
```
	private removeListener(subId: string, callback: (payload: any) => any) {
		if (this.subListeners[subId].length === 1) {
			delete this.subListeners[subId];
			return;
		}
		this.subListeners[subId] = this.subListeners[subId].filter((fn: any) => fn !== callback);
	}
```

and because sub listener wasn't added by that point `this.subListeners[subId].length` throws an error `TypeError: Cannot read properties of undefined (reading 'length')`

**Comment by jbojcic1** [comment]
So seems like sub listener is only added to `this.subListeners` after mint responds with the message about successful subscribe command, while the removal is attempted immediately when the caller calls cancel which means that removal can be attempted before it was even added which results in this error. Thus one way to resolve this issue could be to also do the removal only after mint responds to unsubscribe command.

**Comment by Egge21M** [comment]
That is a great catch. Thank you for bringing this up.

You are absolutely right. The subListener will only be present if the mint has acknowledged the subscription. In this case we should change the cancelation handler to remove the RPC Listener if the mint has not yet responded and remove the subListener otherwise. Send the "unsub" command in both cases.

**Comment by jbojcic1** [comment]
> In this case we should change the cancelation handler to remove the RPC Listener if the mint has not yet responded and remove the subListener otherwise. Send the "unsub" command in both cases.

Yeah that should work as well. Can I create a PR?

**Comment by jbojcic1** [comment]
@Egge21M here it is https://github.com/cashubtc/cashu-ts/pull/302

**Comment by Egge21M** [comment]
Awesome, thank you for your contribution!

**Comment by Egge21M** [comment]
Patch released as 2.5.1

**Comment by jbojcic1** [comment]
@Egge21M after upgrading from 2.4.2 to 2.5.1 I am seeing bunch of issues like:
```
8:16:24 PM [vite] Error when evaluating SSR module /app/lib/cashu/token.ts: failed to import "@cashu/cashu-ts"
|- Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/jbojcic/Projects/prism/boardwalkcash/node_modules/@cashu/cashu-ts/lib/buffer/index.jsx' imported from /Users/jbojcic/Projects/prism/boardwalkcash/node_modules/@cashu/cashu-ts/lib/cashu-ts.es.js
    at finalizeResolution (node:internal/modules/esm/resolve:275:11)
    at moduleResolve (node:internal/modules/esm/resolve:860:10)
    at defaultResolve (node:internal/modules/esm/resolve:984:11)
    at nextResolve (node:internal/modules/esm/hooks:748:28)
    at resolveExtensions (file:///Users/jbojcic/Projects/prism/boardwalkcash/node_modules/tsx/dist/esm/index.mjs?1746814579825:2:2938)
    at async resolveDirectory (file:///Users/jbojcic/Projects/prism/boardwalkcash/node_modules/tsx/dist/esm/index.mjs?1746814579825:2:3538)
    at async resolve (file:///Users/jbojcic/Projects/prism/boardwalkcash/node_modules/tsx/dist/esm/index.mjs?1746814579825:2:4441)
    at async nextResolve (node:internal/modules/esm/hooks:748:22)
    at async Hooks.resolve (node:internal/modules/esm/hooks:240:24)
    at async handleMessage (node:internal/modules/esm/worker:199:18)
```

any idea what could that be? I am not sure I see what could cause it just by checking the release notes

**Comment by jbojcic1** [comment]
Yeah I think it's issue with [this buffer import](https://github.com/cashubtc/cashu-ts/pull/279/files#diff-d0dce76e83a07709eb3481413012471a2121789861bffd69539c5addaf67e11dR6). Seems like package.json is now missing that dep. I'll open a separate bug for that
